### ISSUE TITLE
Incompability with VS Code 1.85.1

### ISSUE THREAD

**Issue by yvesbeutler** [microsoft/vscode-jupyter-keymap#35]
Type: <b>Bug</b>

I am not able to install the whole Jupyter package on my Azure remote. I am able to install the package locally, but not on the remote (I connect trough the Azure ML extension). If I install all the sub-packages manually, I am able to install `Jupyter Cell Tags`, `Jupyter Notebook Renderers` and `Jupyter Slide Show`. It will only fail when I try to install `Jupyter Keymap`.

This is the error message seen in the server log:

```
2024-01-09 09:20:00.336 [error] Failed to install extension. ms-toolsai.jupyter
2024-01-09 09:20:00.336 [error] Incompatible: Can't install 'ms-toolsai.jupyter' extension because it is not compatible with the current version of Visual Studio Code (version 1.85.1).
    at _.O (/home/azureuser/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/server/node/server.main.js:159:32860)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/azureuser/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/server/node/server.main.js:159:23168
    at async Promise.allSettled (index 0)
    at async _.installGalleryExtensions (/home/azureuser/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/server/node/server.main.js:159:23092)
    at async _.installFromGallery (/home/azureuser/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/out/vs/server/node/server.main.js:159:22681)
```

The same VS Code and extension version works well for my colleagues. I already tried the following steps to solve the issue:

- Completely remove all Jupyter extensions from VS Code and reinstall them
- Remove VS Code from Windows, manually delete the extensions folder, then reinstall VS Code + extensions with the same version
- Try a different version of Jupyter

Unfortunately, none of the steps above worked for me.

Extension version: 1.1.2
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.0-1040-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Azure ML: dsw-sentiment-yb-fast|
|OS|Linux x64 5.15.0-1040-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (64 x 2095)|
|Memory (System)|425.12GB (419.06GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vshan820:30294714
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30885897
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t3:30927821

```

</details>

**Comment by yvesbeutler** [comment]
This issue wasn't related to `vscode-jupyter-keymap` therefore I will close it again. Creating a fresh compute instance solved this issue.
